# Generated by Django 3.0.6 on 2020-05-16 21:13

from django.db import migrations, models
import django_countries.fields
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('price_info', django_extensions.db.fields.json.JSONField(blank=True, default={}, null=True, verbose_name='Available price information')),
            ],
        ),
    ]
